apiVersion: v1
kind: ServiceAccount
metadata:
  name: deepseek-ci-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: deepseek-ci@golden-capsule-479805-q9.iam.gserviceaccount.com